"""QuickNotes acceptance kit: black-box checks of the fixed interface.

This file is the lab's definition of "the same product". It never imports
the generated code; it starts `app/server.py` as a separate process and
talks to it over HTTP, exactly as a browser would. Any build that passes
every check here behaves the same, whatever its code looks like.

Do not edit this file to make a build pass. If a check is wrong, fix the
kit deliberately and record why, because changing it changes what "the same
product" means on every machine.
"""

import json
import os
import re
import socket
import subprocess
import sys
import tempfile
import time
import unittest
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
SERVER = PROJECT_ROOT / "app" / "server.py"
REQUIRED_IDS = ("note-text", "add-note", "notes-list", "error")
MAX_LEN = 280


def free_port():
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


class Server:
    """Runs app/server.py on a free port with its own database file."""

    def __init__(self, db_path):
        self.db_path = db_path
        self.port = free_port()
        self.log = tempfile.TemporaryFile()
        env = dict(os.environ, PORT=str(self.port), NOTES_DB=str(db_path))
        self.proc = subprocess.Popen(
            [sys.executable, str(SERVER)],
            cwd=str(PROJECT_ROOT),
            env=env,
            stdout=self.log,
            stderr=subprocess.STDOUT,
        )
        self._wait_until_up()

    def _wait_until_up(self, timeout=10.0):
        deadline = time.time() + timeout
        while time.time() < deadline:
            if self.proc.poll() is not None:
                raise RuntimeError("app/server.py exited early:\n" + self.output())
            try:
                with socket.create_connection(("127.0.0.1", self.port), timeout=0.5):
                    return
            except OSError:
                time.sleep(0.1)
        self.stop()
        raise RuntimeError(f"app/server.py did not listen on PORT={self.port} within {timeout}s")

    def output(self):
        self.log.seek(0)
        return self.log.read().decode(errors="replace")[-2000:]

    def stop(self):
        if self.proc.poll() is None:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()
                self.proc.wait()
        self.log.close()

    def request(self, method, path, body=None, raw=None):
        """Returns (status, headers, body_bytes); never raises on 4xx/5xx."""
        data = raw if raw is not None else (json.dumps(body).encode() if body is not None else None)
        req = urllib.request.Request(f"http://127.0.0.1:{self.port}{path}", data=data, method=method)
        if data is not None:
            req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=5) as resp:
                return resp.status, resp.headers, resp.read()
        except urllib.error.HTTPError as err:
            return err.code, err.headers, err.read()

    def json(self, method, path, body=None, raw=None):
        status, _, payload = self.request(method, path, body, raw)
        return status, (json.loads(payload) if payload else None)


def is_iso8601(value):
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
        return True
    except (AttributeError, ValueError):
        return False


class QuickNotesAcceptance(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.db = Path(self.tmp.name) / "notes.db"
        self.server = Server(self.db)

    def tearDown(self):
        self.server.stop()
        self.tmp.cleanup()

    def add(self, text):
        return self.server.json("POST", "/api/notes", {"text": text})

    def assertError(self, status, body, expected_status, message=None):
        self.assertEqual(status, expected_status)
        self.assertIsInstance(body, dict, "error responses must be a JSON object")
        self.assertIn("error", body)
        if message is not None:
            self.assertEqual(body["error"], message)

    def test_01_page_has_required_elements(self):
        """GET / serves an HTML page with the note-text, add-note, notes-list and error elements"""
        status, headers, html = self.server.request("GET", "/")
        self.assertEqual(status, 200)
        self.assertIn("text/html", headers.get("Content-Type", ""))
        html = html.decode()
        for element_id in REQUIRED_IDS:
            self.assertRegex(html, rf"id\s*=\s*[\"']{element_id}[\"']", f"missing id={element_id}")

    def test_02_page_script_uses_api(self):
        """The page's JavaScript (inline or a linked .js file) calls /api/notes"""
        _, _, html = self.server.request("GET", "/")
        html = html.decode()
        scripts = [html]
        for src in re.findall(r"<script[^>]*\bsrc\s*=\s*[\"']([^\"']+)[\"']", html):
            path = urllib.parse.urljoin("/", src)
            status, _, js = self.server.request("GET", path)
            self.assertEqual(status, 200, f"script {src} not served")
            scripts.append(js.decode())
        self.assertTrue(any("/api/notes" in s for s in scripts), "no script references /api/notes")

    def test_03_list_starts_empty(self):
        """A new database starts with an empty list"""
        status, body = self.server.json("GET", "/api/notes")
        self.assertEqual(status, 200)
        self.assertEqual(body, [])

    def test_04_create_returns_note(self):
        """POST /api/notes returns 201 and the note with id, text and an ISO-8601 created_at"""
        status, note = self.add("Buy milk")
        self.assertEqual(status, 201)
        self.assertIsInstance(note["id"], int)
        self.assertEqual(note["text"], "Buy milk")
        self.assertTrue(is_iso8601(note["created_at"]), f"not ISO-8601: {note['created_at']!r}")

    def test_05_list_newest_first(self):
        """GET /api/notes lists notes newest first"""
        _, first = self.add("first")
        _, second = self.add("second")
        status, notes = self.server.json("GET", "/api/notes")
        self.assertEqual(status, 200)
        self.assertEqual([n["id"] for n in notes], [second["id"], first["id"]])
        self.assertEqual([n["text"] for n in notes], ["second", "first"])

    def test_06_text_is_trimmed(self):
        """Leading and trailing whitespace is removed before saving"""
        status, note = self.add("   hello world  \n")
        self.assertEqual(status, 201)
        self.assertEqual(note["text"], "hello world")

    def test_07_empty_text_rejected(self):
        """Empty text is rejected with 400 "text is required" """
        status, body = self.add("")
        self.assertError(status, body, 400, "text is required")
        self.assertEqual(self.server.json("GET", "/api/notes")[1], [])

    def test_08_whitespace_text_rejected(self):
        """Whitespace-only text is rejected with 400 "text is required" """
        status, body = self.add("   \t  ")
        self.assertError(status, body, 400, "text is required")

    def test_09_max_length_accepted(self):
        """Exactly 280 characters is accepted"""
        status, note = self.add("a" * MAX_LEN)
        self.assertEqual(status, 201)
        self.assertEqual(len(note["text"]), MAX_LEN)

    def test_10_over_max_length_rejected(self):
        """281 characters is rejected with 400 "text must be at most 280 characters" """
        status, body = self.add("a" * (MAX_LEN + 1))
        self.assertError(status, body, 400, "text must be at most 280 characters")
        self.assertEqual(self.server.json("GET", "/api/notes")[1], [])

    def test_11_invalid_json_rejected(self):
        """A body that isn't valid JSON is rejected with 400"""
        status, _, payload = self.server.request("POST", "/api/notes", raw=b"{not json")
        self.assertEqual(status, 400)
        body = json.loads(payload) if payload else None
        self.assertError(status, body, 400)

    def test_12_delete_removes_note(self):
        """DELETE /api/notes/<id> returns 204 and the note is gone from the list"""
        _, keep = self.add("keep me")
        _, gone = self.add("delete me")
        status, _, _ = self.server.request("DELETE", f"/api/notes/{gone['id']}")
        self.assertEqual(status, 204)
        notes = self.server.json("GET", "/api/notes")[1]
        self.assertEqual([n["id"] for n in notes], [keep["id"]])

    def test_13_delete_unknown_404(self):
        """Deleting an id that doesn't exist returns 404 "note not found" """
        status, body = self.server.json("DELETE", "/api/notes/999999")
        self.assertError(status, body, 404, "note not found")

    def test_14_notes_survive_restart(self):
        """Notes are still there after the server restarts with the same NOTES_DB"""
        self.add("remember me")
        self.server.stop()
        self.server = Server(self.db)
        notes = self.server.json("GET", "/api/notes")[1]
        self.assertEqual([n["text"] for n in notes], ["remember me"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
